
[[guide]]
path = "pages/1_guide.py"
name = "ä½¿ç”¨èª¬æ˜"
icon = "ğŸ“•"

[["é »é“æµé‡"]]
path = "pages/2_channel_ranking.py"
name = "æµé‡æ’å"
icon = "ğŸ“ƒ"

[["é »é“æµé‡"]]
path = "pages/3_channel_daily_views.py"
name = "æ¯æ—¥æµé‡"
icon = "ğŸ“ƒ"

[["é »é“æµé‡"]]
path = "pages/4_video_views.py"
name = "å½±ç‰‡æµé‡"
icon = "ğŸ“ƒ"

